require'nvim-treesitter'.setup {
  ignore_install = {},
  modules = {},
  sync_install = false,
  auto_install = true,
  highlight = {
    enable = true
  },
  ensure_installed = {
    'astro',
    'bash',
    'c_sharp',
    'css',
    'dockerfile',
    'gitignore',
    'go',
    'gomod',
    'html',
    'javascript',
    'json',
    'json5',
    'lua',
    'make',
    'markdown',
    'php',
    'proto',
    'rust',
    'sql',
    'tsx',
    'typescript',
    'yaml',
    'zig',
  },
}
